version: "3.9"

services:

  sigma-sports-scraper:
    build:
      context: sigma_sports_scraper
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/pedalprice
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pedalprice
    ports:
      - "5432:5432"
